workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    -OAS:
        inputs:
            - location: registry.speakeasyapi.dev/midday/midday/midday-api:main
        registry:
            location: registry.speakeasyapi.dev/midday/midday/-oas
targets:
    midday:
        target: python
        source: -OAS
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/midday/midday/-oas-python-code-samples
            labelOverride:
                fixedValue: Python (SDK)
            blocking: false
