"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from midday.types import BaseModel
from typing_extensions import TypedDict


class CreateTagTypedDict(TypedDict):
    name: str
    r"""The name of the tag."""


class CreateTag(BaseModel):
    name: str
    r"""The name of the tag."""
