"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from midday.types import BaseModel
from typing_extensions import TypedDict


class DeleteTransactionsResponseTypedDict(TypedDict):
    id: str
    r"""Transaction ID (UUID)."""


class DeleteTransactionsResponse(BaseModel):
    id: str
    r"""Transaction ID (UUID)."""
