"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from midday.types import BaseModel
from midday.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class DeleteInboxItemRequestTypedDict(TypedDict):
    id: str


class DeleteInboxItemRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


class DeleteInboxItemResponseTypedDict(TypedDict):
    r"""Response schema for a successfully deleted inbox item."""

    id: str
    r"""The unique identifier of the deleted inbox item."""


class DeleteInboxItemResponse(BaseModel):
    r"""Response schema for a successfully deleted inbox item."""

    id: str
    r"""The unique identifier of the deleted inbox item."""
