"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from midday.types import BaseModel
from midday.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class DeleteInvoiceRequestTypedDict(TypedDict):
    id: str


class DeleteInvoiceRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


class DeleteInvoiceResponseTypedDict(TypedDict):
    r"""Delete a invoice by its unique identifier for the authenticated team."""

    id: str
    r"""Unique identifier for the deleted invoice"""


class DeleteInvoiceResponse(BaseModel):
    r"""Delete a invoice by its unique identifier for the authenticated team."""

    id: str
    r"""Unique identifier for the deleted invoice"""
