"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from midday.types import BaseModel
from midday.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class DeleteTrackerProjectRequestTypedDict(TypedDict):
    id: str


class DeleteTrackerProjectRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


class DeleteTrackerProjectResponseTypedDict(TypedDict):
    r"""Tracker project deleted successfully."""

    id: str
    r"""Unique identifier of the project to delete"""


class DeleteTrackerProjectResponse(BaseModel):
    r"""Tracker project deleted successfully."""

    id: str
    r"""Unique identifier of the project to delete"""
