"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from midday.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class ExpensesResultArrayTypedDict(TypedDict):
    date_: str
    r"""Date for the expense value"""
    value: float
    r"""Expense value for the given date"""
    currency: str
    r"""Currency code (ISO 4217)"""
    recurring: float
    r"""Recurring expense value for the given date"""
    total: float
    r"""Total expense for the given date"""


class ExpensesResultArray(BaseModel):
    date_: Annotated[str, pydantic.Field(alias="date")]
    r"""Date for the expense value"""

    value: float
    r"""Expense value for the given date"""

    currency: str
    r"""Currency code (ISO 4217)"""

    recurring: float
    r"""Recurring expense value for the given date"""

    total: float
    r"""Total expense for the given date"""
