"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from midday.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class GetBurnRateResponseSchemaTypedDict(TypedDict):
    date_: str
    r"""Date for the burn rate value"""
    value: float
    r"""Burn rate value for the given date"""
    currency: str
    r"""Currency code (ISO 4217)"""


class GetBurnRateResponseSchema(BaseModel):
    date_: Annotated[str, pydantic.Field(alias="date")]
    r"""Date for the burn rate value"""

    value: float
    r"""Burn rate value for the given date"""

    currency: str
    r"""Currency code (ISO 4217)"""
