"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .profitmeta import ProfitMeta, ProfitMetaTypedDict
from .profitresultitem import ProfitResultItem, ProfitResultItemTypedDict
from .profitsummary import ProfitSummary, ProfitSummaryTypedDict
from midday.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class GetProfitResponseSchemaTypedDict(TypedDict):
    summary: ProfitSummaryTypedDict
    meta: ProfitMetaTypedDict
    result: List[ProfitResultItemTypedDict]


class GetProfitResponseSchema(BaseModel):
    summary: ProfitSummary

    meta: ProfitMeta

    result: List[ProfitResultItem]
