"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .revenuemeta import RevenueMeta, RevenueMetaTypedDict
from .revenueresultitem import RevenueResultItem, RevenueResultItemTypedDict
from .revenuesummary import RevenueSummary, RevenueSummaryTypedDict
from midday.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class GetRevenueResponseSchemaTypedDict(TypedDict):
    summary: RevenueSummaryTypedDict
    meta: RevenueMetaTypedDict
    result: List[RevenueResultItemTypedDict]


class GetRevenueResponseSchema(BaseModel):
    summary: RevenueSummary

    meta: RevenueMeta

    result: List[RevenueResultItem]
