"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .profitcurrent import ProfitCurrent, ProfitCurrentTypedDict
from .profitpercentage import ProfitPercentage, ProfitPercentageTypedDict
from .profitprevious import ProfitPrevious, ProfitPreviousTypedDict
from midday.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class ProfitResultItemTypedDict(TypedDict):
    date_: str
    r"""Date for the metric (ISO 8601)"""
    precentage: ProfitPercentageTypedDict
    current: ProfitCurrentTypedDict
    previous: ProfitPreviousTypedDict


class ProfitResultItem(BaseModel):
    date_: Annotated[str, pydantic.Field(alias="date")]
    r"""Date for the metric (ISO 8601)"""

    precentage: ProfitPercentage

    current: ProfitCurrent

    previous: ProfitPrevious
