"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from midday.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class ProfitSummaryTypedDict(TypedDict):
    current_total: float
    r"""Total profit for the current period"""
    prev_total: float
    r"""Total profit for the previous period"""
    currency: str
    r"""Currency code (ISO 4217)"""


class ProfitSummary(BaseModel):
    current_total: Annotated[float, pydantic.Field(alias="currentTotal")]
    r"""Total profit for the current period"""

    prev_total: Annotated[float, pydantic.Field(alias="prevTotal")]
    r"""Total profit for the previous period"""

    currency: str
    r"""Currency code (ISO 4217)"""
