"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from midday.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class ProfitCurrentTypedDict(TypedDict):
    date_: str
    r"""Date for the current value"""
    value: float
    r"""Current value"""
    currency: str
    r"""Currency code (ISO 4217)"""


class ProfitCurrent(BaseModel):
    date_: Annotated[str, pydantic.Field(alias="date")]
    r"""Date for the current value"""

    value: float
    r"""Current value"""

    currency: str
    r"""Currency code (ISO 4217)"""
