"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from midday.types import BaseModel
from typing_extensions import TypedDict


class ProfitPercentageStatus(str, Enum):
    r"""Status of the change"""

    NEGATIVE = "negative"
    POSITIVE = "positive"


class ProfitPercentageTypedDict(TypedDict):
    value: float
    r"""Percentage change compared to previous period"""
    status: ProfitPercentageStatus
    r"""Status of the change"""


class ProfitPercentage(BaseModel):
    value: float
    r"""Percentage change compared to previous period"""

    status: ProfitPercentageStatus
    r"""Status of the change"""
