"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from midday.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class ProfitPreviousTypedDict(TypedDict):
    date_: str
    r"""Date for the previous value"""
    value: float
    r"""Previous value"""
    currency: str
    r"""Currency code (ISO 4217)"""


class ProfitPrevious(BaseModel):
    date_: Annotated[str, pydantic.Field(alias="date")]
    r"""Date for the previous value"""

    value: float
    r"""Previous value"""

    currency: str
    r"""Currency code (ISO 4217)"""
