"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from midday.types import BaseModel
from typing_extensions import TypedDict


class ProfitMetaType(str, Enum):
    r"""Type of metric"""

    PROFIT = "profit"


class ProfitMetaTypedDict(TypedDict):
    type: ProfitMetaType
    r"""Type of metric"""
    currency: str
    r"""Currency code (ISO 4217)"""


class ProfitMeta(BaseModel):
    type: ProfitMetaType
    r"""Type of metric"""

    currency: str
    r"""Currency code (ISO 4217)"""
