"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from midday.types import BaseModel
from typing_extensions import TypedDict


class RevenueMetaType(str, Enum):
    r"""Type of metric"""

    REVENUE = "revenue"


class RevenueMetaTypedDict(TypedDict):
    type: RevenueMetaType
    r"""Type of metric"""
    currency: str
    r"""Currency code (ISO 4217)"""


class RevenueMeta(BaseModel):
    type: RevenueMetaType
    r"""Type of metric"""

    currency: str
    r"""Currency code (ISO 4217)"""
