"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .tagresponse import TagResponse, TagResponseTypedDict
from midday.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class TagsResponseTypedDict(TypedDict):
    data: List[TagResponseTypedDict]
    r"""List of tags."""


class TagsResponse(BaseModel):
    data: List[TagResponse]
    r"""List of tags."""
