"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from midday.types import BaseModel, Nullable, UNSET_SENTINEL
from midday.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateTeamByIDRequestBodyTypedDict(TypedDict):
    name: NotRequired[str]
    r"""Name of the team or organization. Must be between 2 and 32 characters"""
    email: NotRequired[str]
    r"""Primary contact email address for the team"""
    logo_url: NotRequired[str]
    r"""URL to the team's logo image. Must be hosted on midday.ai domain"""
    base_currency: NotRequired[str]
    r"""Base currency for the team in ISO 4217 format (3-letter currency code)"""


class UpdateTeamByIDRequestBody(BaseModel):
    name: Optional[str] = None
    r"""Name of the team or organization. Must be between 2 and 32 characters"""

    email: Optional[str] = None
    r"""Primary contact email address for the team"""

    logo_url: Annotated[Optional[str], pydantic.Field(alias="logoUrl")] = None
    r"""URL to the team's logo image. Must be hosted on midday.ai domain"""

    base_currency: Annotated[Optional[str], pydantic.Field(alias="baseCurrency")] = None
    r"""Base currency for the team in ISO 4217 format (3-letter currency code)"""


class UpdateTeamByIDRequestTypedDict(TypedDict):
    id: str
    request_body: NotRequired[UpdateTeamByIDRequestBodyTypedDict]


class UpdateTeamByIDRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    request_body: Annotated[
        Optional[UpdateTeamByIDRequestBody],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None


class UpdateTeamByIDPlan(str, Enum):
    r"""Current subscription plan of the team"""

    TRIAL = "trial"
    STARTER = "starter"
    PRO = "pro"


class UpdateTeamByIDResponseTypedDict(TypedDict):
    r"""Team updated"""

    id: str
    r"""Unique identifier of the team"""
    name: str
    r"""Name of the team or organization"""
    logo_url: Nullable[str]
    r"""URL to the team's logo image"""
    plan: UpdateTeamByIDPlan
    r"""Current subscription plan of the team"""


class UpdateTeamByIDResponse(BaseModel):
    r"""Team updated"""

    id: str
    r"""Unique identifier of the team"""

    name: str
    r"""Name of the team or organization"""

    logo_url: Annotated[Nullable[str], pydantic.Field(alias="logoUrl")]
    r"""URL to the team's logo image"""

    plan: UpdateTeamByIDPlan
    r"""Current subscription plan of the team"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = []
        nullable_fields = ["logoUrl"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
