"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from midday.types import BaseModel
from midday.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateTagRequestBodyTypedDict(TypedDict):
    name: str
    r"""The new name of the tag."""


class UpdateTagRequestBody(BaseModel):
    name: str
    r"""The new name of the tag."""


class UpdateTagRequestTypedDict(TypedDict):
    id: str
    request_body: NotRequired[UpdateTagRequestBodyTypedDict]


class UpdateTagRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    request_body: Annotated[
        Optional[UpdateTagRequestBody],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None
